### ISSUE TITLE
PHP8环境设置OSS错误

### ISSUE THREAD

**Issue by xiaoqy** [yiichou/aliyun-oss-support#125]
系统环境：
CentOS Linux release 7.6.1810 (Core)

Static hostname: localhost
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 20190711105006363114529432776998
           Boot ID: 60ffe2c52ccc4d3291d9ab63c8d76a3b
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64

PHP版本：
PHP 8.0.3 (cli) (built: Apr 27 2021 08:48:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

Nginx版本：
nginx version: nginx/1.19.10

MariaDB版本：
Server version: 10.5.9-MariaDB Source distribution

在 wordpress （5.7.1大陆版本） 中设置 阿里云 OSS 返回
: RequestId:

![image](https://user-images.githubusercontent.com/29647739/116192227-2090ed80-a760-11eb-96d3-92b11606d2ae.png)

请问这是属于PHP版本问题吗？
但我Google了一下。可我不那么认为。
之前服务器使用的是PHP7.2和国外官方版wordpress.org并添加了cn.wordpress.org的语言包，可以正常使用OSS插件。
尝试过从之前服务器scp或rsync克隆plugins目录也没有用。

但在新服务器PHP8版本中OSS内容可以上传，却会出现：
![image](https://user-images.githubusercontent.com/29647739/116193767-6f3f8700-a762-11eb-8444-14219669d52c.png)

阿里云 OSS 使用WP OSS插件上传成功：
![image](https://user-images.githubusercontent.com/29647739/116193807-81212a00-a762-11eb-9aed-0fe344843a41.png)

**Comment by 0xJacky** [comment]
![image](https://user-images.githubusercontent.com/13096985/130614650-ab8f475b-1d09-4c4f-b612-de6ecb897290.png)

https://github.com/iiDestiny/laravel-filesystem-oss/issues/8

研究了一下，这个是 OSS SDK 的锅，插件里的 Release  打包的还是旧版本的 OSS SDK，在这里下载 https://github.com/aliyun/aliyun-oss-php-sdk 之后手动替换就能正常保存配置、上传图片了。

**Comment by devcco** [comment]
@yiichou 大佬抽空把sdk升级一下呗。我目前也是手动替换SDK来支持php8的。

**Comment by cmdsir** [comment]
根据大佬的留言成功解决了升级到PHP8的问题，谢谢。

**Comment by cmdsir** [comment]
> ![image](https://user-images.githubusercontent.com/13096985/130614650-ab8f475b-1d09-4c4f-b612-de6ecb897290.png)
> 
> [iiDestiny/laravel-filesystem-oss#8](https://github.com/iiDestiny/laravel-filesystem-oss/issues/8)
> 
> 研究了一下，这个是 OSS SDK 的锅，插件里的 Release 打包的还是旧版本的 OSS SDK，在这里下载 https://github.com/aliyun/aliyun-oss-php-sdk 之后手动替换就能正常保存配置、上传图片了。

根据大佬的留言成功解决了升级到PHP8的问题，谢谢。

**Comment by yiichou** [comment]
本周修复

**Comment by cmdsir** [comment]
> 本周修复
好的，随时关注，感谢回复。

**Comment by yiichou** [comment]
https://github.com/yiichou/aliyun-oss-support/releases/tag/3.4.0

**Comment by cmdsir** [comment]
> https://github.com/yiichou/aliyun-oss-support/releases/tag/3.4.0

已经更新，暂无异常。感谢。
