### ISSUE TITLE
请问能否上传文件自动重命名

### ISSUE THREAD

**Issue by yuannancheng** [yiichou/aliyun-oss-support#128]
请问能不能增加上传文件自动重命名的选项，比如使用文件MD5命名，或者使用时间戳+随机数命名，这样文件url会更美观一些。

**Comment by yiichou** [comment]
目前没有计划

这个插件的目标是：以最低限度的改动去支持 OSS 存储图片，所以它只关注存储问题

至于图片有什么尺寸格式、如何命名都是 Wordpress 自身控制的

如果你有类似的需求，可以直接在主题中 hook Wordpress 的上传函数（尽可能早），应该是可以实现的（我没试过）
