### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）。

### ISSUE THREAD

**Issue by 36304099** [yiichou/aliyun-oss-support#95]
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in D:\xxxxxx\web\wp-content\plugins\aliyun-oss\aliyun-oss.php on line 32

**Comment by 36304099** [comment]
手工上传安装的  <aliyun-oss-3.2.7.zip>, 启用后,上面弹出的提示.

**Comment by 36304099** [comment]
wordpress 版本  5.1.1版本   ,新建的站,还没发布任何东西.

**Comment by IvanChou** [comment]
你还在使用 php 5.2 ？
