### ISSUE TITLE
设置文章封面后，封面地址是网站域名而不是OSS的

### ISSUE THREAD

**Issue by VulgarGenius** [yiichou/aliyun-oss-support#97]
所有文章的封面图都无法显示，全部都是指向的本地路径，而不是OSS的。
Wordpress版本：5.2.1

**Comment by zhuhangyu** [comment]
好像这个插件只能做到把图片上传到oss，但文章里面显示的还是本机的图片，域名也没变？

**Comment by IvanChou** [comment]
检查一下 后台-媒体库 中的图片 url，如果是 OSS 地址，那可能就是主题的问题咯

**Comment by AyoCrazy** [comment]
> 检查一下 后台-媒体库 中的图片 url，如果是 OSS 地址，那可能就是主题的问题咯

@IvanChou ，媒体库的url是oss地址。试了几个主题都是这样，有什么好的解决方法吗？

**Comment by IvanChou** [comment]
> @IvanChou ，媒体库的url是oss地址。试了几个主题都是这样，有什么好的解决方法吗？

发个主题出来看看呗

**Comment by zhuhangyu** [comment]
> > @IvanChou ，媒体库的url是oss地址。试了几个主题都是这样，有什么好的解决方法吗？
> 
> 发个主题出来看看呗

看我的https://www.only1server.com/
知更鸟主题

**Comment by IvanChou** [comment]
> 看我的https://www.only1server.com/
> 知更鸟主题

@zhuhangyu 

收费主题啊，我怎么看 (╯‵□′)╯︵┻━┻
